### ISSUE TITLE
:question: Support `torch.hub` based featurizers in main package or plugin?

### ISSUE THREAD

**Issue by cwognum** [datamol-io/molfeat#31]
It would be useful to support loading models via [`torch.hub`](https://pytorch.org/docs/stable/hub.html). I am not aware of any featurizers that would immediately benefit from this (any featurizers that you can think of?), but this would at least comprise another easy-to-use, familiar method by which users can contribute their featurizers to `molfeat`.

Do you think this makes sense? And if so, should it be part of the core package (since we list `torch` as a dependency already, this makes sense to me) or should we rather implement this as a plugin?

**Comment by maclandrol** [comment]
> It would be useful to support loading models via [`torch.hub`](https://pytorch.org/docs/stable/hub.html). I am not aware of any featurizers that would immediately benefit from this (any featurizers that you can think of?), but this would at least comprise another easy-to-use, familiar method by which users can contribute their featurizers to `molfeat`.

This was originally planned and even prototyped, however I faced a wall and had to scratch all of it because of the following reasons:

- Running dependencies. Although you could list dependencies required to load the model (mainly `torch`) in the `hubconf`, it's harder to specify dependencies needed to run the model (this part is still manageable) 
- It does not solve the issues around the input to the model (smiles/selfies tokens ? graphs ? a pre-featurization like fingerprints?, any preprocessing of the inputs etc) so you get the model, but it's not clear how to use it.

Happy to test ideas you might have.
