### ISSUE TITLE
Drop support for mordred

### ISSUE THREAD

**Issue by jstlaurent** [datamol-io/molfeat#63]
### Motivation

[Mordred](https://github.com/mordred-descriptor/mordred) is no longer being developed and updated. The Numpy [1.24.0 release](https://github.com/numpy/numpy/releases/tag/v1.24.0) made changes that remove type aliases used by Mordred, causing incorrect featurization.

### Pitch

Since Mordred usage is limited and compatibility with Numpy is essential, support for Mordred should be removed from Molfeat.

### Additional context

If demand grows large enough, we could consider forking the Mordred repo and maintaining it ourselves. This would have to be balanced with the resources we have available and the current team projects.

**Comment by JacksonBurns** [comment]
@jstlaurent I have just started a fork of mordred ([`morded-community`](https:///ww.github.com/JacksonBurns/mordred-community)) since I have more time to maintain, and I have integrated many of the outstanding PRs that have (hopefully) fixed all the problems. Any interest in adding it back, under a new name?

**Comment by maclandrol** [comment]
@JacksonBurns feel free to make a PR to add it back here, the code should be almost the same as the one we just refactored out. 

We usually request that dependencies be on `conda-forge` too. 

Thanks !
