### ISSUE TITLE
Generate 3D conformers in documentation

### ISSUE THREAD

**Issue by miquelduranfrigola** [datamol-io/molfeat#89]
### 📖 Documentation

Hello!

Thanks for a great and very useful library. I am a bit confused with the documentation of the featurizers that require 3D information. In the documentation, we find something like this:

```
import datamol as dm
from molfeat.trans.fp import FPVecTransformer
smiles = dm.freesolv().iloc[:100].smiles
# sanitize and standardize your molecules if needed
# <generate 3D coordinates here>
transformer = FPVecTransformer(kind='usrcat', dtype=float)
features = transformer(smiles)
```

I do not understant what should we do in place of `<generate 3D coordinates here>`. The input of `transformer` is anyways a list of SMILES, so why should we be generating 3D coordinates before? Are these 3D coordinates being generated as part of the internal procedure of the transformer, or should we generate them separately?

Thanks so much in advance!

**Comment by kkovary** [comment]
@miquelduranfrigola I was also confused recently and found this to work:
```python
import datamol as dm
from rdkit.Chem import AllChem
from molfeat.trans.fp import FPVecTransformer
smiles = dm.freesolv().iloc[:100].smiles

# Convert SMILES to molecules and generate 3D coordinates
mols = [dm.to_mol(s, add_hs=True) for s in smiles]
mols_3d = []
for mol in mols:
    AllChem.EmbedMolecule(mol)
    mols_3d.append(mol)

transformer = FPVecTransformer(kind='usrcat', dtype=float)
features = transformer(mols_3d)
```

would be great to double check with the maintainers that this is the intended way to interface with this transformer and if so the documentation should be updated.

**Comment by maclandrol** [comment]
Hi @miquelduranfrigola, thanks for reporting this.  It's is a typo in the doc.  It should read:

```python

smiles = dm.freesolv().iloc[:100].smiles
smiles = dm.freesolv().iloc[:100].smiles
# sanitize and standardize your molecules if needed
# <generate 3D coordinates here>

transformer = FPVecTransformer(kind='usrcat', dtype=float)
# molecules_with_3D contains the list of molecules with 3D data you have generated <--
features = transformer(molecules_with_3D) 
```

The `Transformers` accept both SMILES and RDKit Mol objects as input.  We have chosen to not compute the conformers on the fly for descriptors that require it, because the **conformer variant you use will impact the representation**. We therefore want that to be intentional by the user (there is a decorator that checks if you are providing molecules with 3D coordinates for USR and other shape descriptors and raise an error accordingly). 

@kkovary provided a nice example of how to compute the 3D coordinates. Again, think carefully about which conformer would make sense for your task (the one with minimal energy ? a random one ? the bioactive one ? one coming from a docking experiment ? etc) 

You can also use datamol to compute the conformers:

```python 
import datamol as dm
from molfeat.trans.fp import FPVecTransformer

smiles = dm.freesolv().iloc[:50].smiles
# sanitize and standardize your molecules if needed

# <generate 3D coordinates here>
mols = [dm.to_mol(s) for s in smiles]
molecules_with_3D = [dm.conformers.generate(m, n_confs=1, minimize_energy=True) for m in mols]

transformer = FPVecTransformer(kind='usrcat', dtype=float)
features = transformer(molecules_with_3D) 
```

If you are reading molecules from SDF with 3D coordinate info available, then you can use the molecules directly as input. 

```python
import datamol as dm
from molfeat.trans.fp import FPVecTransformer
# we are reading from an SDF that contains the 3D coordinates already
molecules_with_3D = dm.read_sdf("https://raw.githubusercontent.com/datamol-io/datamol/main/datamol/data/cdk2.sdf") 
features = transformer(molecules_with_3D) 
```

**Comment by mercuryseries** [comment]
@maclandrol Type fixed in the doc: https://molfeat.datamol.io/featurizers/usrcat

**Comment by miquelduranfrigola** [comment]
Thank you all! Very useful
